syntax = "proto3";

option csharp_namespace = "Wallet.GrpcContracts";

package wallet.v1;

enum WalletServiceType {
  WALLET_SERVICE_TYPE_GENERAL = 0;
  WALLET_SERVICE_TYPE_TRAVEL = 1;
  WALLET_SERVICE_TYPE_FOOD = 2;
  WALLET_SERVICE_TYPE_SHOP = 3;
}

enum LedgerTransactionType {
  LEDGER_TRANSACTION_TYPE_TOP_UP = 0;
  LEDGER_TRANSACTION_TYPE_PAYMENT = 1;
  LEDGER_TRANSACTION_TYPE_HOLD = 2;
  LEDGER_TRANSACTION_TYPE_CAPTURE = 3;
  LEDGER_TRANSACTION_TYPE_RELEASE = 4;
  LEDGER_TRANSACTION_TYPE_REFUND = 5;
  LEDGER_TRANSACTION_TYPE_PROMO_CONSUME = 6;
}
